#!/usr/bin/env python3
"""
init_profile.py

Manage the user's North-Star profile (`.job-hunter-profile.md` in their workspace). The
profile captures preferences that don't show up on a resume but heavily influence which
postings are worth pursuing. See references/profile-questions.md for the 5 questions and
rationale.

Three subcommands:
  init    - emit a fresh template the agent can fill in conversationally
  read    - parse an existing profile.md into structured JSON for the agent
  exists  - check whether a profile.md exists in a given workspace (exit 0 if yes,
            exit 1 if no); useful for the Phase 1 gate

The profile is INTENTIONALLY plain markdown so the user can read and edit it directly
between sessions. The script parses headings + answer blocks; partial answers and
"unknown" markers are preserved.

Usage:
    python init_profile.py init --workspace /path/to/user/workspace
    python init_profile.py read --workspace /path/to/user/workspace
    python init_profile.py exists --workspace /path/to/user/workspace
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PROFILE_FILENAME = ".job-hunter-profile.md"

# Five canonical questions. Keys are stable identifiers; the script uses them as JSON
# field names and as the markdown heading slugs in the rendered profile.
QUESTIONS = [
    ("archetype", "Target archetype",
     "Beyond your job title, what KIND of role do you want? IC, tech lead, "
     "people manager, founding/zero-to-one, or something else?"),
    ("deal_breakers", "Deal-breakers",
     "What absolutely won't work? (No on-call, no travel, no commission-only, "
     "no defense work, no specific company X, etc.)"),
    ("company_size", "Company-size preference",
     "Pre-seed / Series A startup, Series B-C, Series D+ late stage, public "
     "mid-cap, public large-cap, or no preference? Any allergies?"),
    ("mission_vs_comp", "Mission vs comp priority",
     "When forced to choose: 'mission within ±15% of comp', 'comp first always', "
     "'mission first if at least 80% of comp', or 'show me real tradeoffs first'?"),
    ("tolerance", "Tolerance dimensions",
     "Yes/no/depends for each: (a) on-call rotation, (b) >20% travel, (c) office-required "
     "4-5 days. 'Depends on what' is a fine answer."),
]


TEMPLATE = """# North-Star Profile

> Generated by job-hunter init_profile.py. This file stays in your workspace — it is
> NOT committed to the skill or anywhere outside your local folder. The dot-prefix on
> the filename hides it from most `git add .` patterns, but verify your own .gitignore
> if you keep sensitive answers here.
>
> Update freely between sessions. The agent will read this file on each run; if it's
> more than 90 days old, the agent will ask whether anything has changed.

**Created:** {created}
**Last updated:** {created}

{question_blocks}

## Notes (free-form, optional)

[Anything else the agent should know that isn't covered above. Industries you care about,
specific companies on a target list, geographic constraints beyond city, etc.]

"""

QUESTION_BLOCK_TEMPLATE = """## {heading}

> {prompt}

**Answer:** [your answer here, or "unknown" if you'd rather not say]
"""


def _profile_path(workspace: Path) -> Path:
    return workspace / PROFILE_FILENAME


def render_template(created: str = "unset") -> str:
    blocks = "\n".join(
        QUESTION_BLOCK_TEMPLATE.format(heading=heading, prompt=prompt)
        for _, heading, prompt in QUESTIONS
    )
    return TEMPLATE.format(created=created, question_blocks=blocks)


def init_profile(workspace: Path, force: bool = False) -> Path:
    """Write a fresh profile template to the workspace. Idempotent — refuses to
    overwrite an existing profile unless force=True."""
    workspace.mkdir(parents=True, exist_ok=True)
    path = _profile_path(workspace)
    if path.exists() and not force:
        raise FileExistsError(
            f"profile already exists at {path}; pass --force to overwrite, "
            f"or call 'read' to load the existing answers"
        )
    from datetime import datetime
    created = datetime.now().strftime("%Y-%m-%d")
    path.write_text(render_template(created=created), encoding="utf-8")
    return path


def parse_profile(text: str) -> dict:
    """Parse a profile.md into a dict of {question_key: answer_text}."""
    result = {}
    headings_by_key = {key: heading for key, heading, _ in QUESTIONS}

    for key, heading, _prompt in QUESTIONS:
        # Find the heading, then find the "**Answer:**" line under it, capture until
        # the next "## " heading or end of file.
        pattern = re.compile(
            r"^##\s+" + re.escape(heading) + r"\s*$"
            r".*?"
            r"^\*\*Answer:\*\*\s*(.*?)(?=^##\s+|\Z)",
            re.MULTILINE | re.DOTALL,
        )
        match = pattern.search(text)
        if not match:
            result[key] = None
            continue
        answer = match.group(1).strip()
        # Strip a literal placeholder if the user never edited the file
        if answer.startswith("[your answer here"):
            result[key] = None
        else:
            result[key] = answer

    # Parse the optional notes block
    notes_match = re.search(
        r"^##\s+Notes.*?\n(.*?)(?=^##\s+|\Z)", text, re.MULTILINE | re.DOTALL
    )
    if notes_match:
        notes_text = notes_match.group(1).strip()
        if notes_text and not notes_text.startswith("[Anything else"):
            result["notes"] = notes_text
        else:
            result["notes"] = None
    else:
        result["notes"] = None

    # Surface the last_updated date if present
    last_updated_match = re.search(r"^\*\*Last updated:\*\*\s*(\S+)", text, re.MULTILINE)
    if last_updated_match:
        result["_last_updated"] = last_updated_match.group(1)

    return result


def read_profile(workspace: Path) -> dict:
    path = _profile_path(workspace)
    if not path.exists():
        raise FileNotFoundError(f"no profile at {path}")
    text = path.read_text(encoding="utf-8")
    return parse_profile(text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser("init", help="write a fresh profile template")
    p_init.add_argument("--workspace", required=True, type=Path,
                        help="user's workspace folder (where the profile will live)")
    p_init.add_argument("--force", action="store_true",
                        help="overwrite existing profile if present")

    p_read = sub.add_parser("read", help="parse an existing profile to JSON")
    p_read.add_argument("--workspace", required=True, type=Path)

    p_exists = sub.add_parser("exists", help="exit 0 if profile present, 1 if not")
    p_exists.add_argument("--workspace", required=True, type=Path)

    args = parser.parse_args(argv)

    if args.cmd == "init":
        try:
            path = init_profile(args.workspace, force=args.force)
        except FileExistsError as e:
            print(f"error: {e}", file=sys.stderr)
            return 2
        except OSError as e:
            print(f"error: cannot write profile: {e}", file=sys.stderr)
            return 2
        print(f"wrote profile template to {path}", file=sys.stderr)
        print(json.dumps({"path": str(path), "questions": [
            {"key": k, "heading": h, "prompt": p} for k, h, p in QUESTIONS
        ]}, indent=2))
        return 0

    if args.cmd == "read":
        try:
            data = read_profile(args.workspace)
        except FileNotFoundError as e:
            print(f"error: {e}", file=sys.stderr)
            return 1
        except OSError as e:
            print(f"error: cannot read profile: {e}", file=sys.stderr)
            return 2
        print(json.dumps(data, indent=2))
        return 0

    if args.cmd == "exists":
        path = _profile_path(args.workspace)
        return 0 if path.exists() else 1

    return 2


if __name__ == "__main__":
    sys.exit(main())
